export const companyLabels = {
  en: {
    product: "SinFleet ERP",
    companyPanel: "Company Panel",
    loginTitle: "Company Login",
    dashboard: "Dashboard",
    vehicles: "Vehicles",
    drivers: "Drivers",
    clients: "Clients",
    trips: "Trips",
    diesel: "Diesel",
    expenses: "Expenses",
    payments: "Payments",
    outstanding: "Outstanding",
    reports: "Reports",
    vehicleProfit: "Vehicle Profit",
    driverPerformance: "Driver Performance",
    clientLedger: "Client Ledger",
    documentExpiry: "Document Expiry",
    totalIncome: "Total Income",
    dieselCost: "Diesel Cost",
    otherExpense: "Other Expense",
    pendingPayment: "Pending Payment",
    netProfit: "Net Profit",
    totalVehicles: "Total Vehicles",
    activeVehicles: "Active Vehicles",
    onTrip: "On Trip",
    maintenance: "Maintenance",
    expiringDocuments: "Expiring Documents",
    createVehicle: "Add Vehicle",
    editVehicle: "Edit Vehicle",
    createDriver: "Add Driver",
    editDriver: "Edit Driver",
    createClient: "Add Client",
    editClient: "Edit Client",
    createTrip: "New Trip",
    editTrip: "Edit Trip",
    createDiesel: "Add Diesel",
    editDiesel: "Edit Diesel",
    createExpense: "Add Expense",
    editExpense: "Edit Expense",
    createPayment: "Add Payment",
    editPayment: "Edit Payment",
    searchVehicles: "Search vehicle number, make, model",
    searchDrivers: "Search name, phone, license",
    searchClients: "Search client, phone, GST",
    searchTrips: "Search trip, place, vehicle, driver, client",
    searchDiesel: "Search pump, bill, vehicle, driver, trip",
    searchExpenses: "Search paid to, bill, vehicle, driver, trip",
    searchPayments: "Search client, trip, reference, notes",
    searchOutstanding: "Search client, trip, vehicle, route",
    status: "Status",
    vehicleType: "Vehicle Type",
    all: "All"
  },
  hi: {
    product: "सिनफ्लीट ईआरपी",
    companyPanel: "कंपनी पैनल",
    loginTitle: "कंपनी लॉगिन",
    dashboard: "डैशबोर्ड",
    vehicles: "वाहन",
    drivers: "ड्राइवर",
    clients: "ग्राहक",
    trips: "ट्रिप",
    diesel: "डीजल",
    expenses: "खर्चे",
    payments: "पेमेंट",
    outstanding: "बकाया",
    reports: "रिपोर्ट",
    vehicleProfit: "वाहन प्रॉफिट",
    driverPerformance: "ड्राइवर प्रदर्शन",
    clientLedger: "ग्राहक लेजर",
    documentExpiry: "डॉक्यूमेंट एक्सपायरी",
    totalIncome: "कुल आय",
    dieselCost: "डीजल खर्च",
    otherExpense: "अन्य खर्च",
    pendingPayment: "बकाया पेमेंट",
    netProfit: "नेट प्रॉफिट",
    totalVehicles: "कुल वाहन",
    activeVehicles: "सक्रिय वाहन",
    onTrip: "ट्रिप पर",
    maintenance: "मेंटेनेंस",
    expiringDocuments: "खत्म होने वाले डॉक्यूमेंट",
    createVehicle: "वाहन जोड़ें",
    editVehicle: "वाहन एडिट करें",
    createDriver: "ड्राइवर जोड़ें",
    editDriver: "ड्राइवर एडिट करें",
    createClient: "ग्राहक जोड़ें",
    editClient: "ग्राहक एडिट करें",
    createTrip: "नई ट्रिप",
    editTrip: "ट्रिप एडिट करें",
    createDiesel: "डीजल जोड़ें",
    editDiesel: "डीजल एडिट करें",
    createExpense: "खर्चा जोड़ें",
    editExpense: "खर्चा एडिट करें",
    createPayment: "पेमेंट जोड़ें",
    editPayment: "पेमेंट एडिट करें",
    searchVehicles: "वाहन नंबर, मेक, मॉडल खोजें",
    searchDrivers: "नाम, फोन, लाइसेंस खोजें",
    searchClients: "ग्राहक, फोन, जीएसटी खोजें",
    searchTrips: "ट्रिप, जगह, वाहन, ड्राइवर, ग्राहक खोजें",
    searchDiesel: "पंप, बिल, वाहन, ड्राइवर, ट्रिप खोजें",
    searchExpenses: "पेमेंट, बिल, वाहन, ड्राइवर, ट्रिप खोजें",
    searchPayments: "ग्राहक, ट्रिप, रेफरेंस, नोट्स खोजें",
    searchOutstanding: "ग्राहक, ट्रिप, वाहन, रूट खोजें",
    status: "स्थिति",
    vehicleType: "वाहन प्रकार",
    all: "सभी"
  }
} as const;
